### PR TITLE
Make metric_set() and tweak_metric() play nice together

### LINKED ISSUE #351: metric_tweak and metric_set doesn't work together
Originally found here https://stackoverflow.com/questions/75034496/tidymodels-f-meas-metric-tweak-error-on-metric-set

``` r
library(yardstick)
#> For binary classification, the first factor level is assumed to be the event.
#> Use the argument `event_level = "second"` to alter this as needed.

f_meas_weighted <- metric_tweak("f_meas_weighted", f_meas, estimator = "macro_weighted")

f_meas_weighted(iris, truth = Species, estimate = Species)
#> # A tibble: 1 × 3
#>   .metric         .estimator     .estimate
#>   <chr>           <chr>              <dbl>
#> 1 f_meas_weighted macro_weighted         1

metric_set(f_meas_weighted)(iris, truth = Species, estimate = Species)
#> Error in `metric_set()`:
#> ! Failed to compute `f_meas_weighted()`.
#> Caused by error in `f_meas.data.frame()`:
#> ! formal argument "estimator" matched by multiple actual arguments

#> Backtrace:
#>     ▆
#>  1. └─metric_set(f_meas_weighted)(iris, truth = Species, estimate = Species)
#>  2.   └─base::mapply(...) at yardstick/R/metrics.R:351:6
#>  3.     └─yardstick (local) `<fn>`(dots[[1L]][[1L]], dots[[2L]][[1L]])
#>  4.       └─base::tryCatch(...) at yardstick/R/metrics.R:561:2
#>  5.         └─base (local) tryCatchList(expr, classes, parentenv, handlers)
#>  6.           └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
#>  7.             └─value[[3L]](cond)
#>  8.               └─rlang::abort(message, parent = cnd, call = call("metric_set")) at yardstick/R/metrics.R:567:6
```

<sup>Created on 2023-01-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by EmilHvitfeldt**
Will close #351.

``` r
library(yardstick)

f_meas_weighted <- metric_tweak("f_meas_weighted", f_meas, estimator = "macro_weighted")

f_meas_weighted(iris, truth = Species, estimate = Species)
#> # A tibble: 1 × 3
#>   .metric         .estimator     .estimate
#>   <chr>           <chr>              <dbl>
#> 1 f_meas_weighted macro_weighted         1

metric_set(f_meas_weighted)(iris, truth = Species, estimate = Species)
#> # A tibble: 1 × 3
#>   .metric         .estimator     .estimate
#>   <chr>           <chr>              <dbl>
#> 1 f_meas_weighted macro_weighted         1
```

<sup>Created on 2023-02-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### CODE REVIEW

File: R/metrics.R [hunk 1]
```diff
@@ -568,3 +574,13 @@ eval_safely <- function(expr, expr_nm, data = NULL, env = caller_env()) {
     }
   )
 }
+
+
+call_remove_duplicate_arguments <- function(call) {
```
Comment (EmilHvitfeldt) [inline R/metrics.R:579]: All the work happens in this function.

It looks at the arguments that were sets in the function created by `tweak_metric()` and if there are any (like `na_rm` or `estimator` it will zap them from the call object. This way they don't get used twice

File: R/metrics.R [hunk 2]
```diff
@@ -568,3 +574,13 @@ eval_safely <- function(expr, expr_nm, data = NULL, env = caller_env()) {
...
+  arg_names <- environment(call[[1]])[["fixed"]]
```
Comment (DavisVaughan) [inline R/metrics.R:580]: This is mainly what worries me.

What if `metric_tweak()` stored the names of the "static" tweaked arguments as an attribute of the function it returned? i.e. imagine that `metric_tweak("f_meas_weighted", f_meas, estimator = "macro_weighted")` stored `"estimator"` as an attribute named `static` on the result. Then you could do:

```r
call_remove_static_arguments <- function(call, fn) {
  static <- get_static_arguments(fn)
  
  if (length(static) == 0L) {
    # No static arguments
    return(call)
  }
  
  names <- rlang::call_args_names(call)
  names <- intersect(names, static)
  
  if (length(names) == 0L) {
    # `static` arguments don't intersect with `call`
    return(call)
  }
  
  zaps <- rlang::rep_named(names, list(rlang::zap()))
  call <- call_modify(call, !!!zaps)
  
  call
}
```

And in the file where `metric_tweak()` lives you could define these two helpers to help you get and set the `static` attribute

```r
get_static_arguments <- function(fn) {
  attr(fn, "static", exact = TRUE)
}
set_static_arguments <- function(fn, static) {
  attr(fn, "static") <- static
  fn
}
```

File: R/metrics.R [hunk 3]
```diff
@@ -430,6 +434,8 @@ make_numeric_metric_function <- function(fns) {
     # Construct calls from the functions + arguments
     calls <- lapply(fns, call2, !!! call_args)
 
+    calls <- lapply(calls, call_remove_duplicate_arguments)
+
     # Evaluate
     metric_list <- mapply(
       FUN = eval_safely,
```
Comment (DavisVaughan) [inline R/metrics.R:441]: Just putting this somewhere:

At the end of the `@details` section of `metric_set()`, after it talks about the function signatures that it generates, you may want to mention something like:

> If `metric_tweak()` has been used to "tweak" one of these arguments, like `estimator` or `event_level`, then the tweaked version wins. This allows you to set the `estimator` on a metric by metric basis if needed.
